# core/management/commands/seed_data.py
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from core.models import QAEntry

class Command(BaseCommand):
    help = "Seed 10 users and sample Q&A"

    def handle(self, *args, **kwargs):
        for i in range(1, 11):
            username = f"user{i}"
            if not User.objects.filter(username=username).exists():
                user = User.objects.create_user(username=username, password="password123")
            else:
                user = User.objects.get(username=username)
            # sample question
            QAEntry.objects.create(
                user=user,
                question_text=f"What is the purpose of the rotor in an induction motor? (sample {i})",
                answer_text="The rotor is the rotating part that interacts with the rotating magnetic field generated by the stator to produce torque.",
                plugin_source="seed",
            )
        self.stdout.write(self.style.SUCCESS("Seeded 10 users and Q&A entries."))
